### ISSUE TITLE
Any implementation for inference with the ArguGPT model?

### ISSUE THREAD

**Issue by ryuryukke** [huhailinguist/ArguGPT#3]
Hi, thank you for your great work.

I could not find your official implementation for detection with the ArguGPT model.
Do you have any plans to make that available to the public?

Thanks.

**Comment by huhailinguist** [comment]
Hi there, if you check out the readme file, our models are actually available on huggingface e.g.: https://huggingface.co/SJTU-CL/RoBERTa-large-ArguGPT

**Comment by ryuryukke** [comment]
Sorry my question was unclear, I knew the model was available on huggingface, but is there an implementation code for the detection using ArguGPT?

Thanks.

**Comment by yikang0131** [comment]
Hi, we have released two detectors (document-level and sentence-level)

Note that the document should be no longer than 512 tokens for doc-level detector. While there is no upper limit for sent-level detector (but it takes longer for gpu/cpu to predict the results).

You can deploy the doc-level detector as following:
```Python
from transformers import pipeline
pipe = pipeline("text-classification", model="SJTU-CL/RoBERTa-large-ArguGPT")
result = pipe({your_essay})[0]
label, prob = result['label'], result['score']
```

To implement the sent-level detector, you can refer to the codes in our huggingface space: https://huggingface.co/spaces/SJTU-CL/argugpt-detector/blob/main/app.py 
We first split the essay into sentences, predicting the label and prob of each sentence (``predict_one_sent``); then we compute the overall score of the whole document (``predict_doc``)

**Comment by ryuryukke** [comment]
Thank you so much for your detailed comments! I'll close this issue.
